config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :tubecam_devices
  resources :sequences
  resources :users

  get '/standorte' => 'maps#index', as: 'maps'
  get '/projekt', to: 'pages#project', as: 'project'
  get '/projekt/dataexport', to: 'pages#dataexport', as: 'dataexport'
  get '/kontakt', to: 'pages#contact', as: 'contact'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  get '/exports', to: 'exports#index', as: 'exports'

  get '/annotations' => 'annotations#index', as: 'annotations'
  get '/annotations/new' => 'annotations#new', as: 'new_annotation'
  get '/annotations/specific/:id' => 'annotations#specific', as: 'specific_annotation'
  get '/annotations/done' => 'annotations#done'
  get '/annotations/destroy/:id' => 'annotations#destroy', as: 'destroy_annotation'
  post '/annotations' => 'annotations#create'

  # Deactivate instead of Destroy
  get '/sequences/deactivate/:id' => 'sequences#deactivate', as: 'deactivate_sequence'
  get '/sequences/activate/:id' => 'sequences#activate', as: 'activate_sequence'
  get '/sequences/verify/:id' => 'sequences#verify', as: 'verify_annotation'
  get '/sequences/unverify/:id' => 'sequences#unverify', as: 'unverify_annotation'
  get '/tubecam_devices/deactivate/:id' => 'tubecam_devices#deactivate', as: 'deactivate_tubecam_device'
  get '/tubecam_devices/activate/:id' => 'tubecam_devices#activate', as: 'activate_tubecam_device'
  get '/users/deactivate/:id' => 'users#deactivate', as: 'deactivate_user'
  get '/users/activate/:id' => 'users#activate', as: 'activate_user'

  post '/welcome/setup' => 'welcome#setup', as: 'welcome_setup'
  get '/welcome/config' => 'welcome#config', as: 'welcome_config'

  root 'welcome#index'

  get '*path', :to => 'application#page_not_found'
  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :tubecam_devices, :dependent => :destroy

  def active_for_authentication?
    #remember to call the super
    #then put our own check to determine "active" state using
    #our own "is_active" column
    super && self.active?
  end

  def after_confirmation
    self.active = true
    self.spotter_role = true
    save
  end
end

app/controllers/users_controller.rb
##
# Handles users requests, provides CRUD functions. Provides possibility
# to activated or deactivated a user.
##
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy activate deactivate]

  load_and_authorize_resource

  # Lists all useers
  def index
    @users = User.all.order(:id)
  end

  # Shows a specific user
  def show
  end

  # Edits user
  def edit
    if User.find(params[:id]).username == 'admin'
      redirect_to user_path(@user.id), alert: t('flash.users.user_not_editable')
    end
  end

  # Saves user to database
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to action: 'index', notice: t('flash.users.create_success')
    else
      render :new
    end
  end

  # Updates user in database
  def update
    if @user.update(user_params)
      redirect_to action: 'index', notice: t('flash.users.update_success')
    else
      render :edit
    end
  end

  # Destroys user
  def destroy
    @user.destroy
    redirect_to users_url, notice: t('flash.users.destroy_success')
  end

  # Sets user inactive
  def deactivate
    if current_user.admin_role? && @user.update(active: false)
      redirect_to users_path, notice: t('flash.users.deactivate_success')
    else
      redirect_to users_path, alert: t('flash.users.deactivate_fail')
    end
  end

  # Sets user active
  def activate
    if current_user.admin_role? && @user.update(active: true)
      redirect_to users_path, notice: t('flash.users.activate_success')
    else
      redirect_to users_path, alert: t('flash.users.activate_fail')
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :username, :firstname, :lastname, :spotter_role, :verified_spotter_role, :trapper_role, :admin_role, :active, :trapper_role, :admin_role)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

    <div class="field">
      <%= f.label :spotter_role %>
      <%= f.check_box :spotter_role %>
    </div>

    <div class="field">
      <%= f.label :verified_spotter_role %>
      <%= f.check_box :verified_spotter_role %>
    </div>

    <div class="field">
      <%= f.label :trapper_role %>
      <%= f.check_box :trapper_role %>
    </div>

    <div class="field">
      <%= f.label :admin_role %>
      <%= f.check_box :admin_role %>
    </div>

  <div class="actions">
    <%= f.submit (t 'action.save'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% @page_title=t '.title' %>
<h1><%= t '.title'%></h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<% @page_title=t '.title' %>
<h1><%= t '.title' %></h1>

<table class="table table-striped table-sm table-responsive table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th><%= t 'activerecord.attributes.user.username' %></th>
      <th><%= t 'activerecord.attributes.user.firstname' %></th>
      <th><%= t 'activerecord.attributes.user.lastname' %></th>
      <th><%= t 'activerecord.attributes.user.email' %></th>
      <th><%= t 'activerecord.attributes.user.spotter_role' %></th>
      <th><%= t 'activerecord.attributes.user.verified_spotter_role' %></th>
      <th><%= t 'activerecord.attributes.user.trapper_role' %></th>
      <th><%= t 'activerecord.attributes.user.admin_role' %></th>
      <th><%= t 'activerecord.attributes.user.confirmed_at' %></th>
      <th><%= t 'activerecord.attributes.user.active' %></th>
      <% if can? :manage, User %>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tfoot>
  <tr>
    <th>#</th>
    <th><%= t 'activerecord.attributes.user.username' %></th>
    <th><%= t 'activerecord.attributes.user.firstname' %></th>
    <th><%= t 'activerecord.attributes.user.lastname' %></th>
    <th><%= t 'activerecord.attributes.user.email' %></th>
    <th><%= t 'activerecord.attributes.user.spotter_role' %></th>
    <th><%= t 'activerecord.attributes.user.verified_spotter_role' %></th>
    <th><%= t 'activerecord.attributes.user.trapper_role' %></th>
    <th><%= t 'activerecord.attributes.user.admin_role' %></th>
    <th><%= t 'activerecord.attributes.user.confirmed_at' %></th>
    <th><%= t 'activerecord.attributes.user.active' %></th>
    <% if can? :manage, User %>
        <th colspan="3"></th>
    <% end %>
  </tr>
  </tfoot>

  <tbody>
    <% @users.each do |user| %>

      <tr <%= !user.active ? ' class=deleted' : '' %> >
        <td><%= user.id %></td>
        <td><%= user.username %></td>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= user.spotter_role ? '✔' : '-' %></td>
        <td><%= user.verified_spotter_role ? '✔' : '-' %></td>
        <td><%= user.trapper_role ? '✔' : '-' %></td>
        <td><%= user.admin_role ? '✔' : '-' %></td>
        <td><%= user.confirmed_at ? user.confirmed_at.strftime('%d.%m.%y %H:%M') : '-' %></td>
        <td><%= user.active ? '✔' : '-' %></td>
        <% if user.username != 'admin' && (can? :manage, User) %>
          <td><%= link_to (t 'action.edit'), edit_user_path(user) %></td>
        <% else %>
          <td></td>
        <% end %>
        <% if user.username != 'admin' && current_user.admin_role? %>
            <% if user.active? %>
                <td><%= link_to (t 'action.deactivate'), deactivate_user_path(id: user.id) %></td>
            <% else %>
                <td><b><%= link_to (t 'action.activate'), activate_user_path(id: user.id) %></b></td>
            <% end %>
        <% else %>
            <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<% @page_title=t '.title' %>
<h1><%= t '.title' %></h1>

<%= render 'form', user: @user %>

<%= link_to (t 'action.back'), users_path %>

app/views/users/show.html.erb
<% @page_title=t '.title' %>
<p>
  <strong><%= t 'activerecord.attributes.user.email'%></strong>
  <%= @user.email %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.user.username'%></strong>
  <%= @user.username %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.user.firstname'%></strong>
  <%= @user.firstname %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.user.lastname'%></strong>
  <%= @user.lastname %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.user.spotter_role'%></strong>
  <%= @user.spotter_role %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.user.verified_spotter_role'%></strong>
  <%= @user.verified_spotter_role %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.user.trapper_role'%></strong>
  <%= @user.trapper_role %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.user.admin_role'%></strong>
  <%= @user.admin_role %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.user.active'%></strong>
  <%= @user.active %>
</p>
<% if @user.username != 'admin' %>
  <%= link_to (t 'action.edit'), edit_user_path(@user) %> |
<% end %>
<%= link_to (t 'action.back'), users_path %>