config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :tubecam_devices
  resources :sequences
  resources :users

  get '/standorte' => 'maps#index', as: 'maps'
  get '/projekt', to: 'pages#project', as: 'project'
  get '/projekt/dataexport', to: 'pages#dataexport', as: 'dataexport'
  get '/kontakt', to: 'pages#contact', as: 'contact'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  get '/exports', to: 'exports#index', as: 'exports'

  get '/annotations' => 'annotations#index', as: 'annotations'
  get '/annotations/new' => 'annotations#new', as: 'new_annotation'
  get '/annotations/specific/:id' => 'annotations#specific', as: 'specific_annotation'
  get '/annotations/done' => 'annotations#done'
  get '/annotations/destroy/:id' => 'annotations#destroy', as: 'destroy_annotation'
  post '/annotations' => 'annotations#create'

  # Deactivate instead of Destroy
  get '/sequences/deactivate/:id' => 'sequences#deactivate', as: 'deactivate_sequence'
  get '/sequences/activate/:id' => 'sequences#activate', as: 'activate_sequence'
  get '/sequences/verify/:id' => 'sequences#verify', as: 'verify_annotation'
  get '/sequences/unverify/:id' => 'sequences#unverify', as: 'unverify_annotation'
  get '/tubecam_devices/deactivate/:id' => 'tubecam_devices#deactivate', as: 'deactivate_tubecam_device'
  get '/tubecam_devices/activate/:id' => 'tubecam_devices#activate', as: 'activate_tubecam_device'
  get '/users/deactivate/:id' => 'users#deactivate', as: 'deactivate_user'
  get '/users/activate/:id' => 'users#activate', as: 'activate_user'

  post '/welcome/setup' => 'welcome#setup', as: 'welcome_setup'
  get '/welcome/config' => 'welcome#config', as: 'welcome_config'

  root 'welcome#index'

  get '*path', :to => 'application#page_not_found'
  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tubecam_device.rb
class TubecamDevice < ApplicationRecord
  belongs_to :user
  has_many :sequences, :dependent => :destroy

  # Pagination: Amount of items per page
  self.per_page = 15
end

app/controllers/tubecam_devices_controller.rb
##
# Handles tubecam_devices requests, provides CRUD functions. Provides possibility
# to activate or deactivate a tubecam_device.
##
class TubecamDevicesController < ApplicationController
  before_action :set_tubecam_device, only: %i[show edit update destroy activate deactivate]

  load_and_authorize_resource
  skip_before_filter :authenticate_user!
  skip_authorize_resource only: :show

  # Lists all tubecam_devices
  def index
    @tubecam_devices = TubecamDevice.all.order(:id)
    if user_signed_in? &&
       !current_user.admin_role? &&
       current_user.trapper_role?
      @tubecam_devices = @tubecam_devices.where(user_id: current_user.id)
    end

  end

  # Shows a specific tubecam_device (as admin a tubecam_device is also shown
  # even if the deleted attribute is set)
  def show
    @sequences = Sequence.where(tubecam_device_id: @tubecam_device.id)
                     .order(datetime: :desc).page(params[:page])
    if user_signed_in? && !current_user.admin_role?
      @sequences = @sequences.where(deleted: false)
    end
    @thumbnail_url = "https://#{ENV['S3_HOST_NAME']}/#{ENV['S3_BUCKET_NAME']}/thumbnails/"
  end

  # New tubecam_device
  def new
    @tubecam_device = TubecamDevice.new
    @users = User.all.order(username: :asc)
  end

  # Edits tubecam_device
  def edit
    @users = User.all.order(username: :asc)
  end

  # Saves tubecam_device to database
  def create
    @tubecam_device = TubecamDevice.new(tubecam_device_params)
    if @tubecam_device.save
      redirect_to action: 'index', notice: t('flash.tubecam_devices.create_success')
    else
      render :new
    end
  end

  # Updates tubecam_device in database
  def update
    if @tubecam_device.update(tubecam_device_params)
      redirect_to action: 'index', notice: t('flash.tubecam_devices.update_success')
    else
      render :edit
    end
  end

  # Destroys tubecam_device
  def destroy
    @tubecam_device.destroy
    redirect_to tubecam_devices_url, notice: t('flash.tubecam_devices.destroy_success')
  end

  # Sets tubecam_device inactive
  def deactivate
    if current_user.admin_role? && @tubecam_device.update(active: false)
      redirect_to tubecam_devices_path, notice: t('flash.tubecam_devices.deactivate_success')
    else
      redirect_to tubecam_devices_path, alert: t('flash.tubecam_devices.deactivate_fail')
    end
  end

  # Sets tubecam_device active
  def activate
    if current_user.admin_role? && @tubecam_device.update(active: true)
      redirect_to tubecam_devices_path, notice: t('flash.tubecam_devices.activate_success')
    else
      redirect_to tubecam_devices_path, alert: t('flash.tubecam_devices.activate_fail')
    end
  end

  private

  # Common setup or constraints between actions.
  def set_tubecam_device
    @tubecam_device = TubecamDevice.find(params[:id])
  end

  # White listing parameters for 'create'
  def tubecam_device_params
    params.require(:tubecam_device).permit(:serialnumber, :user_id,
                                           :description, :active)
  end

end

app/helpers/tubecam_devices_helper.rb
module TubecamDevicesHelper
end

app/views/tubecam_devices/_form.html.erb
<%= form_for(tubecam_device) do |f| %>
    <% if tubecam_device.errors.any? %>
        <div id='error_explanation'>
          <h2><%= pluralize(tubecam_device.errors.count, 'error') %> prohibited this tubecam_device from being
            saved:</h2>

          <ul>
            <% tubecam_device.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <% if current_user.admin_role? %>
        <div class='field'>
          <%= f.label :serialnumber %>
          <%= f.text_field :serialnumber, :required => true%>
        </div>

        <div class='field'>
          <%= f.label :user_id %>
          <select id='user_id' name='tubecam_device[user_id]' size='1' required>
            <option></option>
            <% @users.each do |user| %>
                <% selected_string = ''
                   if tubecam_device.user_id == user.id
                     selected_string = ' selected="selected" '
                   end
                %>
                <% disabled_string = ''
                   if !user.active?
                     disabled_string = ' disabled="disabled" '
                   end
                %>
                <option <%= selected_string %> <%= disabled_string %> value='<%= user.id %>'>
                  <%= user.username %> (<%= user.firstname %> <%= user.lastname %>)
                </option>
            <% end %>
          </select>
        </div>

    <% end %>

    <div class='field'>
      <%= f.label :description %>
      <%= f.text_area :description, placeholder: (t '.text_area_placeholder') %>
    </div>

    <div class='actions'>
      <%= f.submit (t 'action.save'), class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/tubecam_devices/edit.html.erb
<% @page_title=t '.title' %>
<h1><%= t '.title' %></h1>

<%= render 'form', tubecam_device: @tubecam_device %>

app/views/tubecam_devices/index.html.erb
<% @page_title=t '.title' %>
<h1><%= t '.title' %></h1>

<% if user_signed_in? && current_user.admin_role? %>
    <div class="text-right">
      <%= link_to (t 'action.create'), new_tubecam_device_path, class: 'btn btn-primary' %>
    </div>
<% end %>

<table class="table table-striped table-sm table-responsive table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th><%= t('activerecord.attributes.tubecam_device.serialnumber') %></th>
      <% if current_user.admin_role? %>
        <th><%= t('activerecord.attributes.user.username') %></th>
    <% end %>
    <th><%= t('activerecord.attributes.tubecam_device.description') %></th>
    <th><%= t('activerecord.attributes.tubecam_device.active') %></th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @tubecam_devices.each do |tubecam_device| %>
      <% user = tubecam_device.user %>

      <tr <%= !tubecam_device.active ? ' class=deleted' : '' %> >
        <td><%= tubecam_device.id %></td>
        <td><%= tubecam_device.serialnumber %></td>
        <% if current_user.admin_role? %>
            <td><%= user.username %> (<%= user.id %>)</td>
        <% end %>
        <td><%= tubecam_device.description %></td>
        <td><%= tubecam_device.active ? '✔' : '-' %></td>
        <td><%= link_to (t 'link_to.media'), tubecam_device_path(tubecam_device) %></td>
        <% if current_user.admin_role? || current_user.trapper_role? %>
            <td><%= link_to (t 'action.edit'), edit_tubecam_device_path(tubecam_device) %></td>
        <% end %>
        <% if current_user.admin_role? %>
            <% if tubecam_device.active? %>
                <td><%= link_to (t 'action.deactivate'), deactivate_tubecam_device_path(id: tubecam_device.id) %></td>
            <% else %>
                <td><b><%= link_to (t 'action.activate'), activate_tubecam_device_path(id: tubecam_device.id) %></b></td>
            <% end %>
        <% end %>
      </tr>
  <% end %>
  </tbody>
  <tfoot>
  <tr>
    <th>#</th>
    <th><%= t('activerecord.attributes.tubecam_device.serialnumber') %></th>
    <% if current_user.admin_role? %>
        <th><%= t('activerecord.attributes.user.username') %></th>
    <% end %>
    <th><%= t('activerecord.attributes.tubecam_device.description') %></th>
    <th><%= t('activerecord.attributes.tubecam_device.active') %></th>
    <th colspan="3"></th>
  </tr>
  </tfoot>
</table>

app/views/tubecam_devices/new.html.erb
<% @page_title=t '.title' %>
<h1><%= t '.title' %></h1>

<%= render 'form', tubecam_device: @tubecam_device %>

app/views/tubecam_devices/show.html.erb
<% @page_title=t '.title', number: @tubecam_device.serialnumber %>
<h1><%= @tubecam_device.serialnumber %></h1>
<p><%= @tubecam_device.description %></p>

<h4>
  <%= t '.owner' %> <strong><%= User.find_by(id: @tubecam_device.user_id).username %></strong>
</h4>

<% longitude = @tubecam_device.longitude
   latitude  = @tubecam_device.latitude
   location_text = (t 'link_to.location')
   if !user_signed_in?
     fake_coordinates = Coordinates.fake_coordinates(@tubecam_device.longitude, @tubecam_device.latitude)
     longitude = fake_coordinates['longitude'].truncate
     latitude  = fake_coordinates['latitude'].truncate
     location_text = (t 'link_to.fake_location')
   end %>

<div class='text-right'>
  <%= link_to (t 'link_to.gallery'), sequences_path(tubecam_device_id: @tubecam_device.id), class: 'btn btn-primary' %>
  <%= link_to location_text, maps_path(longitude: longitude, latitude: latitude), class: 'btn btn-primary' %>
</div>


<% if @sequences.empty? %>
  <h4><%= t '.no_media' %></h4>
<% else %>

  <%= will_paginate @sequences %>

  <table class='table table-striped table-sm table-responsive table-hover'>
    <thead>
    <tr>
      <th><%= t 'activerecord.attributes.sequence.sequence_no' %></th>
      <th>Bilder</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @sequences.each do |sequence| %>
        <tr <%= sequence.deleted? ? 'class=deleted' : '' %>>
          <td><%= sequence.sequence_no %></td>
          <td>
            <% sequence.media.limit(5).each do |medium| %>
              <%= link_to image_tag(@thumbnail_url + medium.filename_hash, size: '150x150'), sequence %>
            <% end %>
          </td>
          <td><%= link_to (t 'action.details'), sequence_path(sequence) %></td>
          <% if user_signed_in? && current_user.admin_role? %>
              <% if !sequence.deleted %>
                  <td><%= link_to (t 'action.deactivate'), deactivate_sequence_path(id: sequence.id) %></td>
              <% else %>
                  <td><b><%= link_to (t 'action.activate'), activate_sequence_path(id:sequence.id) %></b></td>
              <% end %>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>

  <%= will_paginate @sequences %>

<% end %>