config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :tubecam_devices
  resources :sequences
  resources :users

  get '/standorte' => 'maps#index', as: 'maps'
  get '/projekt', to: 'pages#project', as: 'project'
  get '/projekt/dataexport', to: 'pages#dataexport', as: 'dataexport'
  get '/kontakt', to: 'pages#contact', as: 'contact'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  get '/exports', to: 'exports#index', as: 'exports'

  get '/annotations' => 'annotations#index', as: 'annotations'
  get '/annotations/new' => 'annotations#new', as: 'new_annotation'
  get '/annotations/specific/:id' => 'annotations#specific', as: 'specific_annotation'
  get '/annotations/done' => 'annotations#done'
  get '/annotations/destroy/:id' => 'annotations#destroy', as: 'destroy_annotation'
  post '/annotations' => 'annotations#create'

  # Deactivate instead of Destroy
  get '/sequences/deactivate/:id' => 'sequences#deactivate', as: 'deactivate_sequence'
  get '/sequences/activate/:id' => 'sequences#activate', as: 'activate_sequence'
  get '/sequences/verify/:id' => 'sequences#verify', as: 'verify_annotation'
  get '/sequences/unverify/:id' => 'sequences#unverify', as: 'unverify_annotation'
  get '/tubecam_devices/deactivate/:id' => 'tubecam_devices#deactivate', as: 'deactivate_tubecam_device'
  get '/tubecam_devices/activate/:id' => 'tubecam_devices#activate', as: 'activate_tubecam_device'
  get '/users/deactivate/:id' => 'users#deactivate', as: 'deactivate_user'
  get '/users/activate/:id' => 'users#activate', as: 'activate_user'

  post '/welcome/setup' => 'welcome#setup', as: 'welcome_setup'
  get '/welcome/config' => 'welcome#config', as: 'welcome_config'

  root 'welcome#index'

  get '*path', :to => 'application#page_not_found'
  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("https://#{ENV['S3_HOST_NAME']}/#{ENV['S3_BUCKET_NAME']}/assets/images/logo_wiesel.png",  class: 'navbar-left logo'), root_path %>
      <%= link_to (t 'link_to.tubecam'), root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links_right' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to (t 'link_to.locations'), maps_path %></li>


<li><%= link_to (t 'link_to.gallery'), sequences_path %></li>


<% if user_signed_in? %>
    <li><%= link_to (t 'link_to.annotate'), new_annotation_path %></li>
<% end %>

<% if user_signed_in? && current_user.trapper_role? && !current_user.admin_role?%>
    <li><%= link_to (t 'link_to.tubecams'), tubecam_devices_path %></li>
<% end %>


<li>
  <% if user_signed_in? %>
      <a href="<%= dashboard_url %>" data-toggle="dropdown"><%= t 'link_to.project' %><b class="caret"></b></a>
      <ul class="dropdown-menu multi-level">
        <% if current_user.admin_role? %>
          <li><a href="<%= exports_path(format: :csv) %>"><%= t 'exports.index.title' %></a></li>
        <% end %>
        <% if current_user.admin_role? %>
          <li><a href="<%= annotations_path %>"><%= t 'annotations.index.title_all_annotations' %></a></li>
        <% else %>
          <li><a href="<%= annotations_path %>"><%= t 'annotations.index.title' %></a></li>
        <% end %>
        <li><a href="<%= project_path %>"><%= t 'pages.project.title' %></a></li>
        <li><a href="<%= contact_path %>"><%= t 'pages.contact.title' %></a></li>
      </ul>
  <% else %>
      <%= link_to (t 'link_to.project'), project_path %>
      </li>
      <li><%= link_to (t 'pages.contact.title'), contact_path %>
  <% end %>
</li>

app/views/layouts/_navigation_links_right.html.erb
<% if user_signed_in? %>
    <% if user_signed_in? && current_user.admin_role? %>
        <li>
          <a href="<%= dashboard_url %>" data-toggle="dropdown"><%= (t 'layouts.navigations.title') %><b class="caret"></b></a>
          <ul class="dropdown-menu multi-level">
            <li><% link_to (t 'layouts.application') %></li>
            <li><a href="<%= dashboard_url %>"><%= t 'link_to.overview' %></a></li>
            <li class="divider"></li>
            <li><a href="<%= users_url %>"><%= t 'link_to.users' %></a></li>
            <li><a href="<%= tubecam_devices_url %>"><%= t 'link_to.tubecam_devices' %></a></li>
          </ul>
        </li>
    <% end %>
    <li><%= link_to current_user.username, edit_user_registration_path %></li>
    <li><%= link_to '<em class="fa fa-sign-out fa-lg" aria-hidden="true"></em>'.html_safe, destroy_user_session_path, :method=>'delete' %></li>
<% else %>
    <li><%= link_to 'Anmelden <em class="fa fa-sign-in fa-lg" aria-hidden="true"></em>'.html_safe, new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title %> - TubeCam</title>
  <%= favicon_link_tag "https://#{ENV['S3_HOST_NAME']}/#{ENV['S3_BUCKET_NAME']}/assets/images/fav_icon.png" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
  <![endif]-->
</head>

<body class="container">
<header>
  <%= render 'layouts/navigation' %>
</header>

<div class="container mainpage">
  <%= yield %>
</div>


<!-- Flash messages -->
<% unless flash.empty? %>
    <script type="text/javascript">
        <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
        toastr['<%= type %>']('<%= f[1] %>');
        <% end %>
    </script>
<% end %>
</body>
</html>