config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :tubecam_devices
  resources :sequences
  resources :users

  get '/standorte' => 'maps#index', as: 'maps'
  get '/projekt', to: 'pages#project', as: 'project'
  get '/projekt/dataexport', to: 'pages#dataexport', as: 'dataexport'
  get '/kontakt', to: 'pages#contact', as: 'contact'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  get '/exports', to: 'exports#index', as: 'exports'

  get '/annotations' => 'annotations#index', as: 'annotations'
  get '/annotations/new' => 'annotations#new', as: 'new_annotation'
  get '/annotations/specific/:id' => 'annotations#specific', as: 'specific_annotation'
  get '/annotations/done' => 'annotations#done'
  get '/annotations/destroy/:id' => 'annotations#destroy', as: 'destroy_annotation'
  post '/annotations' => 'annotations#create'

  # Deactivate instead of Destroy
  get '/sequences/deactivate/:id' => 'sequences#deactivate', as: 'deactivate_sequence'
  get '/sequences/activate/:id' => 'sequences#activate', as: 'activate_sequence'
  get '/sequences/verify/:id' => 'sequences#verify', as: 'verify_annotation'
  get '/sequences/unverify/:id' => 'sequences#unverify', as: 'unverify_annotation'
  get '/tubecam_devices/deactivate/:id' => 'tubecam_devices#deactivate', as: 'deactivate_tubecam_device'
  get '/tubecam_devices/activate/:id' => 'tubecam_devices#activate', as: 'activate_tubecam_device'
  get '/users/deactivate/:id' => 'users#deactivate', as: 'deactivate_user'
  get '/users/activate/:id' => 'users#activate', as: 'activate_user'

  post '/welcome/setup' => 'welcome#setup', as: 'welcome_setup'
  get '/welcome/config' => 'welcome#config', as: 'welcome_config'

  root 'welcome#index'

  get '*path', :to => 'application#page_not_found'
  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sequence.rb
class Sequence < ApplicationRecord
  belongs_to :tubecam_device
  has_many :media, :dependent => :destroy
  has_many :annotation, :dependent => :destroy

  # Use scoping for filteroptions in media gallery
  include Filterable
  scope :tubecam_device_id, -> (tubecam_device_id) { where tubecam_device_id: tubecam_device_id } if !:tubecam_device_id.empty?
  scope :sequence, -> (sequence) { where sequence: sequence } if !:sequence.empty?

  # Pagination: Amount of items per page
  self.per_page = 10

  validates :tubecam_device_id, uniqueness: { scope: :sequence_no }
end

app/controllers/sequences_controller.rb
##
# Handles sequence requests, provides CRUD functions, possibility to
# verify an annotation as verified spotter and applies a filter to
# the sequence gallery
##
class SequencesController < ApplicationController
  before_action :set_sequence, only: %i[show edit update destroy]

  load_and_authorize_resource
  skip_before_filter :authenticate_user!
  skip_authorize_resource only: %i[index show verify unverify]

  # Lists all sequences
  def index
    scope_params = scope_params()
    @filter_params = scope_params
    sequences = Sequence.filter(scope_params)
    sequences = filter_sequences(sequences)
    sequences = sequences.where(deleted: false).order(datetime: :desc)
    @sequences = sequences.page(params[:page])
    @thumbnail_url = "https://#{ENV['S3_HOST_NAME']}/#{ENV['S3_BUCKET_NAME']}/thumbnails/"
    @annotations_lookup_table = AnnotationsLookupTable.all
    @annotations = Annotation.all
    @tubecam_devices = TubecamDevice.where(active: true)
                           .order(serialnumber: :asc)
  end

  # Shows a specific sequence
  def show
    if @sequence.deleted
      redirect_to sequences_path, alert: t('flash.sequences.deactivated')
    end
    sequence = Sequence.find(params[:id])
    @media = sequence.media.order(frame: :asc)
    @media = @media.paginate(per_page: 15, page: params[:page])
    @image_url = "https://#{ENV['S3_HOST_NAME']}/#{ENV['S3_BUCKET_NAME']}/"
    @thumbnail_url = "#{@image_url}thumbnails/"
    @tubecam_device = TubecamDevice.find(sequence.tubecam_device_id)
    @annotations = Annotation.where(sequence_id: sequence.id)
                       .order(verified_id: :asc, created_at: :desc)
    @annotations_lookup_table = AnnotationsLookupTable.all
  end

  # New sequence
  def new
    @sequence = Sequence.new
  end

  # Creates a new sequence
  def create
    @sequence = Sequence.new(sequence_params)
    if @sequence.save
      redirect_to @sequence, notice: t('flash.sequences.create_success')
    else
      render :new
    end
  end

  # Updates a sequence
  def update
    if @sequence.update(sequence_params)
      redirect_to @sequence, notice: t('flash.sequences.update_success')
    else
      render :edit
    end
  end

  # Destroys a sequence
  def destroy
    @sequence.destroy
    redirect_to sequences_url, notice: t('flash.sequences.destroy_success')
  end

  # Deactivates a sequence
  def deactivate
    @sequence = set_sequence
    tubecam_device_id = @sequence.tubecam_device_id
    media = Medium.where(sequence_id: @sequence)
    media.each do |m|
      m.update(deleted: true)
    end
    if (current_user.admin_role? || current_user.trapper_role?) && @sequence.update(deleted: true)
      redirect_to tubecam_device_url(tubecam_device_id), notice: t('flash.sequences.deactivate_success')
    else
      redirect_to tubecam_device_url(tubecam_device_id), alert: t('flash.sequences.deactivate_fail')
    end
  end

  # Activates a sequence
  def activate
    @sequence = set_sequence
    tubecam_device_id = @sequence.tubecam_device_id
    media = Medium.where(sequence_id: @sequence)
    media.each do |m|
      m.update(deleted: false)
    end
    if (current_user.admin_role? || current_user.trapper_role?) && @sequence.update(deleted: false)
      redirect_to tubecam_device_url(tubecam_device_id), notice: t('flash.sequences.activate_success')
    else
      redirect_to tubecam_device_url(tubecam_device_id), alert: t('flash.sequences.activate_fail')
    end
  end

  # Verifies an annotation (possible only for verified spotters)
  def verify
    annotation = Annotation.find(params[:annotation_id])
    if user_signed_in? &&
        current_user.verified_spotter_role? &&
        annotation.update(verified_id: current_user.id)
      redirect_to sequence_path(annotation.sequence.id), notice: t('flash.sequences.verify_success')
    else
      redirect_to sequence_path(annotation.sequence.id), alert: t('flash.sequences.verify_fail')
    end
  end

  # Deletes an annotation's verification (possible only for verified spotters)
  def unverify
    annotation = Annotation.find(params[:annotation_id])
    if user_signed_in? &&
        current_user.verified_spotter_role? &&
        annotation.update(verified_id: nil)
      redirect_to sequence_path(annotation.sequence.id), notice: t('flash.sequences.verification_destroy_success')
    else
      redirect_to sequence_path(annotation.sequence.id), alert: t('flash.sequences.verification_destroy_fail')
    end
  end

  private

  # Common setup or constraints between actions.
  def set_sequence
    @sequence = Sequence.find(params[:id])
  end

  # White listing parameters for 'create' and 'update'
  def sequence_params
    params.require(:sequence).permit(:path, :filename, :sequencestype, :datetime,
                                     :longitude, :latitude, :sequence, :frame,
                                     :tubecam_device_id, :exifdata, :deleted)
    # Additional for filtering gallery
    params.require(:sequence).permit(:date_start, :date_end, :lookup_table_id)
  end

  # White listing parameters for 'index'
  def scope_params
    scope_params = params.slice(:tubecam_device_id, :sequence)
  end

  # Applies a filter by time period and by 'lookup_table_id' (annotation)
  # to the sequences list
  def filter_sequences(sequences)
    sequences = filter_by_start_date(sequences)
    sequences = filter_by_end_date(sequences)
    sequences = filter_by_lookup_table_id(sequences)
    sequences
  end

  # Filters sequences by start date
  def filter_by_start_date(sequences)
    if !params[:date_start].nil? && !params[:date_start].empty?
      @filter_params[:date_start] = string_to_date(params[:date_start],
                                                   '00:00:00')
      filter_date_start = Medium.select(:sequence_id)
                              .where(['datetime >=  ?', @filter_params[:date_start]])
                              .distinct.pluck(:sequence_id)
      !filter_date_start.nil? ? sequences = sequences.where(id: filter_date_start) : nil
    end
    sequences
  end

  # Filters sequences by end date
  def filter_by_end_date(sequences)
    if !params[:date_end].nil? && !params[:date_end].empty?
      @filter_params[:date_end] = string_to_date(params[:date_end], '22:59:59')
      filter_date_end = Medium.select(:sequence_id)
                            .where(['datetime <=  ?', @filter_params[:date_end]])
                            .distinct.pluck(:sequence_id)
      !filter_date_end.nil? ? sequences = sequences.where(id: filter_date_end) : nil
    end
    sequences
  end

  # Filter sequences by lookup_table_id
  def filter_by_lookup_table_id(sequences)
    if !params[:lookup_table_id].nil? && !params[:lookup_table_id].empty?
      @filter_params[:lookup_table_id] = params[:lookup_table_id]
      annotations = filter_by_hierarchy
      sequence_ids = Annotation.where(annotations_lookup_table_id: annotations).select(:sequence_id)
      !annotations.nil? ? sequences = sequences.where(id: sequence_ids) : nil
    end
    sequences
  end

  # Filter sequences by taxonomical hierarchical level (family, genus, species)
  def filter_by_hierarchy
    lookup_table_id = params[:lookup_table_id]
    annotation_id = AnnotationsLookupTable.find(lookup_table_id).annotation_id
    first_digit, second_digit = annotation_id.to_s.split('')
    family_level = /[1-9]00/
    genus_level = /[1-9][1-9]0/
    if family_level.match(annotation_id)
      search = "#{first_digit}[0-9][0-9]"
      annotations = AnnotationsLookupTable.where('annotation_id ~* ?', search)
                        .select(:id).pluck(:id)
    elsif genus_level.match(annotation_id)
      search = "#{first_digit}#{second_digit}[0-9]"
      annotations = AnnotationsLookupTable.where('annotation_id ~* ?', search)
                        .select(:id).pluck(:id)
    else
      annotations = AnnotationsLookupTable.where(annotation_id: annotation_id)
                        .select(:id).pluck(:id)
    end
    annotations
  end

  # Reformats date string
  def string_to_date(date_string, time)
    unless date_string.empty?
      date_start_string = date_string.split('.')
      date_start_string = "#{date_start_string[2]}:#{date_start_string[1]}:#{date_start_string[0]} #{time}"
      date_start = Time.strptime(date_start_string, '%Y:%m:%d %H:%M:%S')
      date_string = date_start
    end
    date_string
  end

end

app/views/sequences/_filter.html.erb
<div class='form-inline'>
  <form action="<%= sequences_path %>" method="get">
    <select id='tubecam_device_id' name='tubecam_device_id' class="form-control" size='1'>
      <option></option>
      <% @tubecam_devices.each do |tubecam| %>
          <% selected_string = ''
             if params[:tubecam_device_id] == tubecam.id.to_s
               selected_string = ' selected="selected" '
             end
             tubecam_owner = User.find_by(id: tubecam.user_id)
          %>
          <option <%= selected_string %> value='<%= tubecam.id %>'>
            <%= tubecam.serialnumber %> (<%= tubecam.user.username %>)
          </option>
      <% end %>
    </select>

    <div class='input-group date' id='datetimepicker-start-icon'>
      <input type='text' name='date_start' class="form-control" id='datetimepicker-start-input'/>
      <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
    </div>

    <div class='input-group date ' id='datetimepicker-end-icon'>
      <input type='text' name='date_end' class='form-control' id='datetimepicker-end-input'/>
      <span class='input-group-addon'><span class='glyphicon glyphicon-calendar'></span></span>
    </div>

    <select id='annotations-select' class="form-control filter-select" name='lookup_table_id' size='1'>
      <option></option>
      <% @annotations_lookup_table.each do |lookup| %>
          <% selected_string = ''
             if params[:lookup_table_id] == lookup.id.to_s
               selected_string = ' selected="selected" '
             end
          %>
          <% disabled_string = ''
             if !lookup.selectable?
               disabled_string = ' disabled="disabled" '
             end
          %>

          <% if !lookup.family.nil? && !lookup.genus.nil?
               displayed_tag = lookup.name + " (" + lookup.genus + " " + lookup.species + ")"
               class_tag = "annotations-level-2"
               space = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.html_safe
             end
             if !lookup.genus.nil? && lookup.name.nil?
               displayed_tag = lookup.genus
               class_tag = "annotations-level-1"
               space = '&nbsp;&nbsp;'.html_safe
             end
             if !lookup.family.nil? && lookup.name.nil?
               displayed_tag = lookup.family
               class_tag = "annotations-level-0"
               space = ''.html_safe
             end
             if lookup.family.nil? && lookup.genus.nil? && lookup.species.nil?
               displayed_tag = lookup.name
               class_tag = "annotations-level-0"
               space = ''.html_safe
             end
          %>
          <option <%= selected_string %> <%= disabled_string %> class=<%= class_tag %> value='<%= lookup.id %>'><%= space %>
            <%= displayed_tag %></option>
      <% end %>
    </select>

    <div class="filter-search-reset">
      <%= button_tag(type: "submit", class: "btn btn-success btn-filter") do %>
          <span class="glyphicon glyphicon-filter"></span> <%= (t 'action.filter') %>
      <% end %>
      <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, sequences_path, class: 'btn btn-warning btn-filter' %>
    </div>
  </form>
</div>
</div>

<%= javascript_include_tag 'media/moment_locale_de-ch' %>
<script type="text/javascript">
    var date_start = '<%= @filter_params[:date_start].to_s %>';
    var date_end = '<%= @filter_params[:date_end].to_s %>';
    $(function () {
        $('#datetimepicker-start-input').datetimepicker({
            format: 'DD.MM.YYYY',
            locale: moment.locale('de-ch'),
            defaultDate: date_start
        });
        $('#datetimepicker-start-icon').datetimepicker({
            format: 'DD.MM.YYYY',
            locale: moment.locale('de-ch'),
            defaultDate: date_start
        });
        $('#datetimepicker-end-input').datetimepicker({
            format: 'DD.MM.YYYY',
            locale: moment.locale('de-ch'),
            defaultDate: date_end
        });
        $('#datetimepicker-end-icon').datetimepicker({
            format: 'DD.MM.YYYY',
            locale: moment.locale('de-ch'),
            defaultDate: date_end
        });
    });
</script>

app/views/sequences/index.html.erb
<% @page_title=t '.title' %>
<h1><%= t '.title' %></h1>

<%= render 'filter' %>

<% if @sequences.empty? %>
    <h3><%= t '.no_media' %></h3>
<% else %>

    <%= will_paginate @sequences %>

    <div class="gallery">
      <% @sequences.each do |sequence| %>
          <% longitude = sequence.media.first.longitude
             latitude  = sequence.media.first.latitude
             if !user_signed_in?
              fake_coordinates = Coordinates.fake_coordinates(longitude, latitude)
                longitude = fake_coordinates['longitude']
                 latitude  = fake_coordinates['latitude']
             end %>


          <div class="sequence-description">
              <% if !Annotation.where(sequence_id: sequence).where.not(verified_id: nil).empty? %>
                <span class="emoji-icon fa-lg" title="<%= (t 'general.alt_text_verified_icon') %>">🎖</span> |
              <% elsif !Annotation.where(sequence_id: sequence).empty? %>
                <span class="emoji-icon fa-lg" title="<%= (t 'general.alt_text_verified_icon') %>">✍️</span> |
              <% end %>
              <%= link_to (t 'activerecord.models.tubecam_device') + ' ' + sequence.tubecam_device.serialnumber, tubecam_device_path(sequence.tubecam_device_id) %>
            | <%= link_to (t 'link_to.sequence') + ' ' + sequence.sequence_no.to_s, sequence_path(sequence.id) %>
              <% if user_signed_in? %>
                |  <%= link_to (t 'link_to.annotate'), controller: 'annotations', action: 'specific', :id => sequence.media.first.id %>
              <% end %>
            | <%= link_to (t 'link_to.location'), maps_path(:longitude => longitude, :latitude => latitude) %>
            | <%= sequence.datetime.strftime("%d.%m.%Y %H:%M:%S") %> Uhr
          </div>
          <div class="sequence">
            <% @media = Medium.where(sequence_id: sequence.id).order(frame: :asc).limit(5) %>
            <% @media.each do |medium| %>
                <div class="item">
                  <%= link_to image_tag(@thumbnail_url + medium.filename_hash), sequence %>
                  <div class="item-actions">
                    <ul>


                    </ul>
                  </div>
                </div>
            <% end %>
          </div>
      <% end %>
    </div>

    <%= will_paginate @sequences %>

<% end %>

app/views/sequences/show.html.erb
<% @page_title=t '.title', number: @sequence.sequence_no.to_s %>
<h1><%= (t 'activerecord.models.sequence') + ' ' + @sequence.sequence_no.to_s %></h1>

<% longitude = @sequence.longitude
   latitude  = @sequence.latitude
   location_text = (t 'link_to.location')
       if !user_signed_in?
     fake_coordinates = Coordinates.fake_coordinates(@sequence.longitude, @sequence.latitude)
     longitude = fake_coordinates['longitude'].truncate
     latitude  = fake_coordinates['latitude'].truncate
     location_text = (t 'link_to.fake_location')
   end %>

<div class="medium-detail">
  <div class="image-description">
    <table class="table table-striped table-sm table-responsive table-hover" style="max-width: 400px;">
      <tr>
        <td><b><%= t 'activerecord.attributes.medium.datetime' %></b></td>
        <td><%= @sequence.datetime.strftime("%d.%m.%Y %H:%M:%S") %></td>
      </tr>
      <% if user_signed_in? %>
      <tr>
        <td><b><%= t '.coordinates' %></b></td>
        <td><%= longitude %>, <%= latitude %></td>
      </tr>
      <% end %>
      <tr>
        <td><b><%= t 'activerecord.attributes.medium.mediatype' %></b></td>
        <td> <%= @sequence.media.first.mediatype %></td>
      </tr>
      <tr>
        <td><b><%= t '.frames' %></b></td>
        <td> <%= @sequence.media.count %></td>
      </tr>
    </table>
  </div>
  <div class="image-links">
    <%= link_to (t 'link_to.tubecam') + ' ' + @tubecam_device.serialnumber, tubecam_device_path(@sequence.tubecam_device_id), class: 'btn btn-primary' %>
    <%= link_to location_text, maps_path(:longitude => longitude, :latitude => latitude), class: 'btn btn-primary' %>
    <% if user_signed_in? && !@annotations.empty? && !@annotations.find_by(user_id: current_user.id) %>
        <%= link_to (t 'link_to.annotate'), {controller: 'annotations', action: 'specific', :id => @sequence.id}, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>


<div class="gallery">
    <%= will_paginate @media %>
  <div class="sequence">
    <% @media.order(frame: :asc).each do |medium| %>
        <div class="item">
          <a href="<%= @image_url + medium.filename_hash %>" data-imagelightbox="f">
            <%= image_tag(@thumbnail_url + medium.filename_hash) %>
          </a>
        </div>
    <% end %>
  </div>
</div>
</div>

<div class="medium-detail">
  <div class="image-links">
    <% if @annotations.empty? %>
        <h4><%= t '.no_annotations' %></h4>
        <%= link_to (t 'link_to.annotate'), {controller: 'annotations', action: 'specific', :id => @media.first.id}, class: 'btn btn-primary' %>
    <% else %>
        <table class="table table-striped table-sm table-responsive table-hover">
          <thead>
          <tr>
            <th><%= t 'activerecord.attributes.annotations_lookup_table.name' %></th>
            <th><%= t 'activerecord.attributes.annotations_lookup_table.genus' %></th>
            <th><%= t 'activerecord.attributes.annotations_lookup_table.species' %></th>
            <th><%= t 'activerecord.attributes.annotations_lookup_table.family' %></th>
            <th><%= t 'activerecord.attributes.annotations_lookup_table.annotation_id' %></th>
            <th><%= t 'activerecord.attributes.annotations_lookup_table.created_at' %></th>
            <th><%= t 'activerecord.attributes.user.username' %></th>
            <th><%= t '.verified' %></th>
            <% if user_signed_in? && current_user.verified_spotter_role? %>
                <th><%= t '.verification' %></th>
            <% end %>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% @annotations.each do |annotation| %>
              <% lookup_id = annotation.annotations_lookup_table_id - 1 %>
              <tr>
                <td><%= @annotations_lookup_table[lookup_id].name %></td>
                <td><%= @annotations_lookup_table[lookup_id].genus %></td>
                <td><%= @annotations_lookup_table[lookup_id].species %></td>
                <td><%= @annotations_lookup_table[lookup_id].family %></td>
                <td><%= @annotations_lookup_table[lookup_id].annotation_id %></td>
                <td><%= annotation.created_at.strftime("%d.%m.%Y %H:%M:%S") %></td>
                <td><%= annotation.user.username %></td>

                <% if annotation.verified_id.nil? %>
                    <td>-</td>
                    <% if !@annotations.where.not(verified_id: nil).empty? %>
                        <td>-</td>
                    <% else %>
                        <% if user_signed_in? && current_user.verified_spotter_role? %>
                            <td><%= link_to (t '.verify'), verify_annotation_path(annotation_id: annotation.id) %></td>
                        <% end %>
                    <% end %>
                <% else %>
                    <td><span class="fa-lg"  title="<%= (t 'general.alt_text_verified_icon') %>">🎖</span></td>
                    <% if user_signed_in? && current_user.verified_spotter_role? %>
                        <td><%= link_to (t '.unverify'), unverify_annotation_path(annotation_id: annotation.id) %></td>
                    <% end %>
                <% end %>

                <% if user_signed_in? && (current_user.id == annotation.user_id || current_user.admin_role? )%>
                    <td><%= link_to (t 'action.destroy'), :controller => 'annotations', :action => 'destroy', :id => annotation.id, :sequence_id => annotation.sequence.id %></td>
                <% else %>
                    <td></td>
                <% end %>

              </tr>
          <% end %>
          </tbody>
        </table>
    <% end %>
  </div>
</div>




<%= javascript_include_tag 'imagelightbox.min' %>
<%= javascript_include_tag 'custom_imagelightbox' %>